### ISSUE TITLE
Describe 'Other packages don't do it right.'

### ISSUE THREAD

**Issue by wheresrhys** [jcoreio/async-throttle#2]
I'm _guessing_ what you're getting at is you can end up with uncaught promise exceptions... or is there something else too?

Would be good to explain properly what this package does that others don't. At present I have no idea if it will solve my problem without digging through your source code

**Comment by jedwards1211** [comment]
Fair enough!  Basically I haven't seen any other packages that actually wait for the throttled function to finish.  For example `p-throttle` with a limit of 1 and delay of 1000 will call your throttled function once a second, even if the previous call hasn't finished.  It doesn't rate-limit the number of calls that are *currently running*, just the speed at which *calls are initiated*.

This package is exactly analogous to lodash's sync `throttle` in that only one call is running at a time and it will wait for the throttled function to finish before calling it again, even it's been more than a second (or whatever desired throttle delay) since the last call.

Does that make sense?  If so I'll add this to the readme.

**Comment by wheresrhys** [comment]
That does make sense. Unfortunately it means it doesn't apply to the issue I'm experiencing, but thanks for the clarification

**Comment by jedwards1211** [comment]
Okay, are you experiencing an issue with this package or with something else?

**Comment by tommedema** [comment]
The other thing p-throttle doesn't do is trailing edge throttles; would be great if this package would resolve that

**Comment by jedwards1211** [comment]
wow 8 days passed already, last week was crazy...

Yeah trailing edge throttles would be cool.  I need to stare at the code and think for awhile about how to implement that in a foolproof way...

**Comment by jedwards1211** [comment]
Also in that case I might ought to think about implementing an async debounce with maxWait as well, and build throttle on top of it, like lodash does for sync throttle
