### ISSUE TITLE
Calling .cancel results in UnhandledRejectionWarning

### ISSUE THREAD

**Issue by satazor** [jcoreio/async-throttle#9]
I'm using the new `.cancel()` feature, but I'm getting an `UnhandledRejectionWarning` in the following situation:

```js
var asyncThrottle = require("@jcoreio/async-throttle");

const myFn = asyncThrottle(() => new Promise((resolve) => setTimeout(resolve, 10)), 1000);

(async () => {
    await myFn().catch(() => {});
    
    await myFn.cancel().catch(() => {));
    console.log('canceled');
})();
```

See: https://runkit.com/satazor/5f75b2c66abf3b001aeff1ea

**Comment by jedwards1211** [comment]
Okay, I realized a potential bug with `.cancel()` and refactored to fix it, and added [your test case](https://github.com/jcoreio/async-throttle/blob/master/test/index.js#L299) and [an assertion that no unhandled rejections occur](https://github.com/jcoreio/async-throttle/blob/master/test/index.js#L67).  This should be fixed in [version 1.3.1](https://github.com/jcoreio/async-throttle/releases/tag/v1.3.1).
